Make get-NWSdata exit with non-zero error code on failed download
NWS changed their files right after we updated get-NWSdata to get the
3 March versions, and delayed implementation until 16 April.

I had previously set up get-NWSdata to exit with a non-zero exit code
if any dbfawk files were out of date, but I failed to make it do so if
any files failed to download.

Had I done so back in commit ee337c07, the automated github testing we
do on every commit would have pointed out the problem to us long ago.
Instead, it was silently "passing" the get-NWSdata test precisely
because it was failing to download any files and wasn't causing an
error exit.

Now, if either download of a file fails *or* dbfawks are out of date,
the script will exit with exit code 1, and it will exit with exit
code 0 only if all downloads succeeded and all dbfawks work.   It will
report at the end which downloads failed and which dbfawks are out of
date.

Had this code been in place earlier, we would have known that NWS
pulled the rug out from under us the day it happened instead of 4
months later and after having inconvenienced users.

C.f. #390

diff --git a/scripts/get-NWSdata.in b/scripts/get-NWSdata.in
--- a/scripts/get-NWSdata.in
+++ b/scripts/get-NWSdata.in
@@ -59,6 +59,8 @@ cd ${prefix}/share/xastir/Counties || exit 1
 #
 rm -f *.zip 2>&1 >/dev/null
 
+exitcode=0
+badfetch=""
 
 # Fetch new copies, unzip into place, delete archive.
 #
@@ -72,8 +74,14 @@ for d in $FILE1 $FILE2 $FILE3 $FILE4 $FILE5 $FILE6; do
     cut=`echo $d|cut -c1-2 -`
     rm -f $cut*.shx $cut*.shp $cut*.dbf $cut*.prj $cut*.zip 2>&1 >/dev/null
     wget https://www.weather.gov/source/gis/Shapefiles/$DIR/$d.zip
-    unzip $d.zip
-    rm -f *.zip
+    if [ $? -ne 0 ]
+    then
+        exitcode=1
+        badfetch="$d.zip $badfetch"
+    else
+        unzip $d.zip
+        rm -f *.zip
+    fi
   fi
 done
 
@@ -108,7 +116,7 @@ done
 ####################
 #
 
-exitcode=0
+baddbfawk=""
 
 for d in $FILE1 $FILE2 $FILE3 $FILE4 $FILE5 $FILE6 $FILE7; do
 
@@ -122,6 +130,7 @@ for d in $FILE1 $FILE2 $FILE3 $FILE4 $FILE5 $FILE6 $FILE7; do
     echo $result
     if [ "$result" = "No matching dbfawk signature found" ]; then
         echo "Fix dbfawk for $e!"
+        baddbfawk="$e $baddbfawk"
         exitcode=1
     fi
   fi
@@ -129,7 +138,8 @@ done
 echo
 
 if [ $exitcode -eq 1 ] ; then
-    echo "One or more dbfawk files is out of date.  Fix the problem."
+    echo "Out-of-date dbfawks: $baddbfawk ."
+    echo "Failed downloads: $badfetch ."
 fi
 
 exit $exitcode
